language: node_js
node_js:
- 'node'
install:
- npm install
script:
- npm run build
after_success: |
  if [ -n "$GITHUB_TOKEN" ]; then
    cd "$TRAVIS_BUILD_DIR"
    cd dist
    git init
    git config user.name "myl cl"
    git config user.email "yunliangmiao@gmail.com"
    git remote add upstream "https://$GITHUB_TOKEN@github.com/myl0204/XiXi.git"
    git fetch upstream
    git reset upstream/gh-pages
    git add -A
    git commit -m "rebuild pages"
    git push -q -f upstream HEAD:gh-pages
  fi